version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        # [Choice] Update 'VARIANT' to pick a .NET Core version: 2.1, 3.1, 5.0
        VARIANT: 11
        # Options
        INSTALL_MAVEN: "true"
        INSTALL_GRADLE: "true"
        INSTALL_NODE: "true"
        NODE_VERSION: "lts/*"
        INSTALL_AZURE_CLI: "true"
        MAVEN_VERSION: "3.6.3"
        GRADLE_VERSION: "6.7.1"
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - ..:/workspace:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)