#Name of the workflow
name: Continuous-Delivery

#Triggers to run the workflow
on:
  workflow_run:
    workflows: ["Continuous-integration"]
    types:
      - completed
  workflow_dispatch:
    branches: [ main, users/** ]

jobs:
  #Release Job
  DEV:
    uses: ./.github/workflows/environment-template.yml
    with:
      environment: "dev"
    secrets: 
      MS_TEAMS_WEBHOOK_URI: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      SERVICEPRINCIPAL_PASSWORD: ${{ secrets.SERVICEPRINCIPAL_PASSWORD }}
      PAT: ${{ secrets.DEVOPS_WITH_GITHUB_PAT }}
      SERVICE_PRINCIPAL_OBJECT_ID: ${{ secrets.SERVICE_PRINCIPAL_OBJECT_ID }}
      SERVICE_PRINCIPAL_CLIENT_ID: ${{ secrets.SERVICE_PRINCIPAL_CLIENT_ID }}

  #Release Job
  QA:
    uses: ./.github/workflows/environment-template.yml
    needs: [DEV]
    with:
      environment: "qa"
    secrets:
      MS_TEAMS_WEBHOOK_URI: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      SERVICEPRINCIPAL_PASSWORD: ${{ secrets.SERVICEPRINCIPAL_PASSWORD }}
      PAT: ${{ secrets.DEVOPS_WITH_GITHUB_PAT }}
      SERVICE_PRINCIPAL_OBJECT_ID: ${{ secrets.SERVICE_PRINCIPAL_OBJECT_ID }}
      SERVICE_PRINCIPAL_CLIENT_ID: ${{ secrets.SERVICE_PRINCIPAL_CLIENT_ID }}

  #Release Job
  PRD:
    uses: ./.github/workflows/environment-template.yml
    needs: [QA]
    with:
      environment: "prd"
    secrets:
      MS_TEAMS_WEBHOOK_URI: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      SERVICEPRINCIPAL_PASSWORD: ${{ secrets.SERVICEPRINCIPAL_PASSWORD }}
      PAT: ${{ secrets.DEVOPS_WITH_GITHUB_PAT }}
      SERVICE_PRINCIPAL_OBJECT_ID: ${{ secrets.SERVICE_PRINCIPAL_OBJECT_ID }}
      SERVICE_PRINCIPAL_CLIENT_ID: ${{ secrets.SERVICE_PRINCIPAL_CLIENT_ID }}
