name: Demo Issue Form Closed

on:
  issues:
    types:
      - closed

jobs:
  parse_issue_labels:
    runs-on: ubuntu-20.04
    outputs:
      user: ${{ steps.generate_variables.outputs.user }}
      organization: ${{ steps.generate_variables.outputs.organization }}
      repository: ${{ steps.generate_variables.outputs.repository }}
    steps:
      - name: Run Issue form parser
        id: parse
        uses: peter-murray/issue-forms-body-parser@v2.0.0
        with:
          issue_id: ${{ github.event.issue.number }}
          separator: '###'
          label_marker_start: '>>'
          label_marker_end: '<<'

      - name: Publish output variables
        uses: actions/github-script@v5
        id: generate_variables
        env:
          demo_payload: ${{ steps.parse.outputs.payload  }}
        with:
          script: |
            demoPayload = JSON.parse(process.env.demo_payload);
            const user = demoPayload['User-Handle'];
            const github_repo = "${{ github.repository }}";
            const myArray = github_repo.split("/");
            const organization = myArray[0];
            const repository = myArray[1];
            core.setOutput('user', `${user}`);
            core.setOutput('organization', `${organization}`);
            core.setOutput('repository', `${repository}`);
  trigger_demo_removal:
    needs:
      - parse_issue_labels
    if: |
      !contains(github.event.issue.labels.*.name, 'bug')
    uses: ./.github/workflows/demo_remove.yml
    with:
      user_name: ${{ needs.parse_issue_labels.outputs.user }}
      organization_name: ${{ needs.parse_issue_labels.outputs.organization }}
      repository_name: ${{ needs.parse_issue_labels.outputs.repository }}
    secrets:
      DEVOPS_WITH_GITHUB_PAT: ${{ secrets.DEVOPS_WITH_GITHUB_PAT }}